name: Build and push docker images

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  presentation-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Marp Build
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          entrypoint: /home/marp/.cli/docker-entrypoint
          args: presentation.md -o docs/index.html --html --title="Optimierung einer VueJS-Web-App" --author="Andreas Nicklaus" --theme-set ./style/rose-pine.css
        env:
          MARP_USER: root:root
      - name: Marp Build
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          entrypoint: /home/marp/.cli/docker-entrypoint
          args: presentation.md -o docs/joi_jwt.pdf --allow-local-files --theme-set ./style/rose-pine.css
        env:
          MARP_USER: root:root
      - name: copy images
        run: sudo cp -r images docs/images
      - name: Deploy production
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/
